name: BuildTest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./ToDoApp/ToDoApp.csproj

      - name: Build
        run: dotnet build ./ToDoApp/ToDoApp.csproj

      - name: Test
        run: dotnet test ./ToDoApp/ToDoApp.csproj
